version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn your_project.wsgi:application --bind 0.0.0.0:8081"
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8081:8081"
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      DEBUG: '0'
      DJANGO_SECRET_KEY: 'your-secret-key'
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis

  celery:
    build: .
    command: celery -A your_project worker -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
